### ISSUE TITLE
Error to setup the environment.

### ISSUE THREAD

**Issue by CharlesDias** [antmicro/visual-system-designer-app#1]
Dear,

I tried to setup the VSD environment. However, I got the error below when I ran the `vsd init workspace` command. 

P.S.: All dependencies were installed.

```
$ vsd init workspace
Traceback (most recent call last):
  File "/home/charlesdias/VIRTUS-CC/antmicro/.venv/bin/vsd", line 5, in <module>
    from vsd.__main__ import main
  File "/home/charlesdias/VIRTUS-CC/antmicro/visual-system-designer-app/vsd/__main__.py", line 15, in <module>
    from vsd.init import init, vsd_update_workspace, vsd_workspace_info
  File "/home/charlesdias/VIRTUS-CC/antmicro/visual-system-designer-app/vsd/init.py", line 11, in <module>
    from enum import StrEnum
ImportError: cannot import name 'StrEnum' from 'enum' (/usr/lib/python3.10/enum.py)
```

Thanks for your help.

**Comment by pgielda** [comment]
StrEnum was introduced in Python 3.11...

**Comment by CharlesDias** [comment]
Thanks @pgielda! It worked!
